// <auto-generated />
using System;
using CorDosOlhos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CorDosOlhos.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CorDosOlhos.Models.Cadastro", b =>
                {
                    b.Property<int>("IdC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BairroC")
                        .HasColumnType("char(25)");

                    b.Property<string>("CEPC")
                        .HasColumnType("char(8)");

                    b.Property<string>("CPFC")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<string>("CidadeC")
                        .HasColumnType("char(25)");

                    b.Property<string>("EmailC")
                        .HasColumnType("char(30)");

                    b.Property<string>("EnderecoC")
                        .HasColumnType("char(25)");

                    b.Property<string>("Etnia")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("NasC")
                        .HasColumnType("date");

                    b.Property<string>("NomeC")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NumeroC")
                        .IsRequired()
                        .HasColumnType("char(7)");

                    b.Property<string>("SobrenomeC")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.Property<string>("TelefoneC")
                        .IsRequired()
                        .HasColumnType("char(13)");

                    b.Property<string>("UFC")
                        .HasColumnType("char(2)");

                    b.HasKey("IdC");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("CorDosOlhos.Models.Contato", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailContato")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.Property<string>("MsgContato")
                        .HasColumnType("char(25)");

                    b.Property<string>("NomeContato")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdContato");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("CorDosOlhos.Models.Registro", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BairroRegistro")
                        .HasColumnType("char(25)");

                    b.Property<string>("CEPRegistro")
                        .HasColumnType("char(8)");

                    b.Property<string>("CidadeRegistro")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DescricaoRegistro")
                        .HasColumnType("char(150)");

                    b.Property<string>("EnderecoRegistro")
                        .IsRequired()
                        .HasColumnType("char(25)");

                    b.Property<string>("NumeroRegistro")
                        .HasColumnType("char(7)");

                    b.Property<string>("PontoRefRegistro")
                        .HasColumnType("char(25)");

                    b.HasKey("IdRegistro");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
